# steps:
#   # Build the container image
#   - name: "gcr.io/cloud-builders/docker"
#     args: [
#         "build", 
#         "-t", "gcr.io/llm-garage/gemma-finetune:latest",
#         "--build-arg",
#         "HF_TOKEN=$_HF_TOKEN",
#         "."
#       ]
#     # Pass the Hugging Face token as a build argument
#     # You'll need to set this as a substitution variable when running the build
#     # or configure it in your Cloud Build trigger.
#     # Example: --substitutions=_HF_TOKEN=your_hf_token_here
#     # If your Dockerfile doesn't need HF_TOKEN, you can remove this.
#     # env: ['HF_TOKEN=${_HF_TOKEN}'] 

#   # Push the container image to Container Registry in llm-garage project
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/llm-garage/gemma-finetune:latest"]

# images:
#   - "gcr.io/llm-garage/gemma-finetune:latest"

# Optional: specify timeout for the build
# timeout: "1200s"
# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - build
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/$_SERVICE'
#       - '--build-arg'
#       - 'HF_TOKEN=$_HF_TOKEN'
#       - '.'
# images:
#   - 'gcr.io/$PROJECT_ID/$_SERVICE'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME'
      - '--build-arg'
      - 'HF_TOKEN=$_HF_TOKEN'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME'
