name: 'Deploy to Cloud Batch Container'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'llm-garage'
  REGION: 'us-central1'
  SERVICE: 'llm-garage-finetune'
  IMAGE_NAME: 'finetune-image'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
        - name: 'Checkout code'
          uses: 'actions/checkout@v4'
    
        - name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
        - name: Set up gcloud CLI
          uses: google-github-actions/setup-gcloud@v2
          with:
            project_id: ${{ env.PROJECT_ID }}

        - name: 'Set up Cloud SDK' # Good practice to explicitly include
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
           project_id: ${{ env.PROJECT_ID }}

        - name: 'Build and Push Docker Image using Cloud Build'
          run: gcloud builds submit . \
                --config cloudbuild.yaml \
                --substitutions=\
                _IMAGE_NAME='${{ env.IMAGE_NAME }}',\
                _HF_TOKEN='${{ secrets.HF_TOKEN }}',\
                --project ${{ env.PROJECT_ID }}

